# -*- coding: utf-8 -*-
"""Flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HqcuUn_UVOhDc0A4Z6ysl2y2l3nwTkg
"""

from flask import Flask, request, jsonify
import joblib

app = Flask(__name__)

# Load the trained model
model1 = joblib.load('dt_model1.pkl')
model2 = joblib.load('rand_frst_model1.pkl')
model3 = joblib.load('svm_model.pkl')
model4 = joblib.load('adb_model.pkl')
model5 = joblib.load('xgb_model.pkl')

def predict():
  data = request.json
  try:
    features = [data[' feature1'], data[' feature2'], data[' feature3'], data[' feature4'], data[' feature5']]
    # Make predictions using the loaded model
    prediction1 = model1.predict
    predection2 = model2.predict
    prediction3 = model3.predict
    prediction4 = model4.predict
    prediction5 = model5.predict
    return jsonify({'prediction1': prediction1, 'prediction2': prediction2, 'prediction3': prediction3, 'prediction4': prediction4, 'prediction5': prediction5})
  except Exception as e:
    return jsonify({'error': str(e)})

  if __name__ == '__main__':
    app.run(debug=True)

